export { default as LandingPage } from "./LandingPage";
export { default as LoginPage } from "./LoginPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as SchoolPage } from "./SchoolPage";
export { default as ClubPage } from "./ClubPage";
export { default as UserSettingsPage } from "./UserSettingsPage";
export { default as SchoolSettingsPage } from "./SchoolSettingsPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as NewClub } from "./NewClub";
